//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WedService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public HoaDonBan()
        {
            this.CTHoaDonBans = new HashSet<CTHoaDonBan>();
        }
    
        public string MaHoaDon { get; set; }
        public string TenDangNhap { get; set; }
        public string TinhTrang { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
        public double TongTien { get; set; }
    
        public virtual ICollection<CTHoaDonBan> CTHoaDonBans { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
