//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WedService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CTHoaDonBans = new HashSet<CTHoaDonBan>();
            this.CTHoaDonNhaps = new HashSet<CTHoaDonNhap>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaLoai { get; set; }
        public int BaoHanh { get; set; }
        public string TinhTrang { get; set; }
        public string LoaiMau { get; set; }
        public string KichCo { get; set; }
        public int SoLuong { get; set; }
        public int Gia { get; set; }
        public int GiaGiam { get; set; }
        public byte[] HinhAnh { get; set; }
    
        public virtual ICollection<CTHoaDonBan> CTHoaDonBans { get; set; }
        public virtual ICollection<CTHoaDonNhap> CTHoaDonNhaps { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
    }
}
