//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormGiayPatin.ServiceReferenceAdmin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NguoiDung", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class NguoiDung : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] HoaDonBansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[] HoaDonNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] HoaDonBans {
            get {
                return this.HoaDonBansField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonBansField, value) != true)) {
                    this.HoaDonBansField = value;
                    this.RaisePropertyChanged("HoaDonBans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[] HoaDonNhaps {
            get {
                return this.HoaDonNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonNhapsField, value) != true)) {
                    this.HoaDonNhapsField = value;
                    this.RaisePropertyChanged("HoaDonNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quyen {
            get {
                return this.QuyenField;
            }
            set {
                if ((this.QuyenField.Equals(value) != true)) {
                    this.QuyenField = value;
                    this.RaisePropertyChanged("Quyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoaDonBan", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class HoaDonBan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[] CTHoaDonBansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayDatHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayGiaoHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung NguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[] CTHoaDonBans {
            get {
                return this.CTHoaDonBansField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonBansField, value) != true)) {
                    this.CTHoaDonBansField = value;
                    this.RaisePropertyChanged("CTHoaDonBans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaHoaDon {
            get {
                return this.MaHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHoaDonField, value) != true)) {
                    this.MaHoaDonField = value;
                    this.RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayDatHang {
            get {
                return this.NgayDatHangField;
            }
            set {
                if ((this.NgayDatHangField.Equals(value) != true)) {
                    this.NgayDatHangField = value;
                    this.RaisePropertyChanged("NgayDatHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayGiaoHang {
            get {
                return this.NgayGiaoHangField;
            }
            set {
                if ((this.NgayGiaoHangField.Equals(value) != true)) {
                    this.NgayGiaoHangField = value;
                    this.RaisePropertyChanged("NgayGiaoHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung NguoiDung {
            get {
                return this.NguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiDungField, value) != true)) {
                    this.NguoiDungField = value;
                    this.RaisePropertyChanged("NguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhTrangField, value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoaDonNhap", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class HoaDonNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[] CTHoaDonNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung NguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[] CTHoaDonNhaps {
            get {
                return this.CTHoaDonNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonNhapsField, value) != true)) {
                    this.CTHoaDonNhapsField = value;
                    this.RaisePropertyChanged("CTHoaDonNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaHoaDon {
            get {
                return this.MaHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHoaDonField, value) != true)) {
                    this.MaHoaDonField = value;
                    this.RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung NguoiDung {
            get {
                return this.NguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiDungField, value) != true)) {
                    this.NguoiDungField = value;
                    this.RaisePropertyChanged("NguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTHoaDonBan", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class CTHoaDonBan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaGiamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan HoaDonBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaCTHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GiaGiam {
            get {
                return this.GiaGiamField;
            }
            set {
                if ((this.GiaGiamField.Equals(value) != true)) {
                    this.GiaGiamField = value;
                    this.RaisePropertyChanged("GiaGiam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan HoaDonBan {
            get {
                return this.HoaDonBanField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonBanField, value) != true)) {
                    this.HoaDonBanField = value;
                    this.RaisePropertyChanged("HoaDonBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaCTHoaDon {
            get {
                return this.MaCTHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaCTHoaDonField, value) != true)) {
                    this.MaCTHoaDonField = value;
                    this.RaisePropertyChanged("MaCTHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSPField, value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BaoHanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[] CTHoaDonBansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[] CTHoaDonNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaGiamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KichCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai PhanLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhTrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaoHanh {
            get {
                return this.BaoHanhField;
            }
            set {
                if ((this.BaoHanhField.Equals(value) != true)) {
                    this.BaoHanhField = value;
                    this.RaisePropertyChanged("BaoHanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[] CTHoaDonBans {
            get {
                return this.CTHoaDonBansField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonBansField, value) != true)) {
                    this.CTHoaDonBansField = value;
                    this.RaisePropertyChanged("CTHoaDonBans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[] CTHoaDonNhaps {
            get {
                return this.CTHoaDonNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonNhapsField, value) != true)) {
                    this.CTHoaDonNhapsField = value;
                    this.RaisePropertyChanged("CTHoaDonNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GiaGiam {
            get {
                return this.GiaGiamField;
            }
            set {
                if ((this.GiaGiamField.Equals(value) != true)) {
                    this.GiaGiamField = value;
                    this.RaisePropertyChanged("GiaGiam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KichCo {
            get {
                return this.KichCoField;
            }
            set {
                if ((object.ReferenceEquals(this.KichCoField, value) != true)) {
                    this.KichCoField = value;
                    this.RaisePropertyChanged("KichCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaiMau {
            get {
                return this.LoaiMauField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiMauField, value) != true)) {
                    this.LoaiMauField = value;
                    this.RaisePropertyChanged("LoaiMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiField, value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSPField, value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai PhanLoai {
            get {
                return this.PhanLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.PhanLoaiField, value) != true)) {
                    this.PhanLoaiField = value;
                    this.RaisePropertyChanged("PhanLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhTrangField, value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhanLoai", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class PhanLoai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[] SanPhamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiField, value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTHoaDonNhap", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class CTHoaDonNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap HoaDonNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaCTHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap HoaDonNhap {
            get {
                return this.HoaDonNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonNhapField, value) != true)) {
                    this.HoaDonNhapField = value;
                    this.RaisePropertyChanged("HoaDonNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaCTHoaDon {
            get {
                return this.MaCTHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaCTHoaDonField, value) != true)) {
                    this.MaCTHoaDonField = value;
                    this.RaisePropertyChanged("MaCTHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSPField, value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAdmin.IAdminWinform")]
    public interface IAdminWinform {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/FindAllNguoiDungResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[] FindAllNguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/FindAllNguoiDungResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[]> FindAllNguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/FindNguoiDungResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[] FindNguoiDung(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/FindNguoiDungResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[]> FindNguoiDungAsync(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DangNhapNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/DangNhapNguoiDungResponse")]
        bool DangNhapNguoiDung(string tendangnhap, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DangNhapNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/DangNhapNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> DangNhapNguoiDungAsync(string tendangnhap, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/InsertNguoiDungResponse")]
        bool InsertNguoiDung(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/InsertNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> InsertNguoiDungAsync(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeleteNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/DeleteNguoiDungResponse")]
        bool DeleteNguoiDung(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeleteNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/DeleteNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> DeleteNguoiDungAsync(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/UpdateNguoiDungResponse")]
        bool UpdateNguoiDung(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateNguoiDung", ReplyAction="http://tempuri.org/IAdminWinform/UpdateNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> UpdateNguoiDungAsync(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllSanPham", ReplyAction="http://tempuri.org/IAdminWinform/FindAllSanPhamResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[] FindAllSanPham();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllSanPham", ReplyAction="http://tempuri.org/IAdminWinform/FindAllSanPhamResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[]> FindAllSanPhamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindSanPham", ReplyAction="http://tempuri.org/IAdminWinform/FindSanPhamResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[] FindSanPham(string tensp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindSanPham", ReplyAction="http://tempuri.org/IAdminWinform/FindSanPhamResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[]> FindSanPhamAsync(string tensp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindMaSanPham", ReplyAction="http://tempuri.org/IAdminWinform/FindMaSanPhamResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham FindMaSanPham(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindMaSanPham", ReplyAction="http://tempuri.org/IAdminWinform/FindMaSanPhamResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham> FindMaSanPhamAsync(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateSoLuong", ReplyAction="http://tempuri.org/IAdminWinform/UpdateSoLuongResponse")]
        bool UpdateSoLuong(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateSoLuong", ReplyAction="http://tempuri.org/IAdminWinform/UpdateSoLuongResponse")]
        System.Threading.Tasks.Task<bool> UpdateSoLuongAsync(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeleteSoLuong", ReplyAction="http://tempuri.org/IAdminWinform/DeleteSoLuongResponse")]
        bool DeleteSoLuong(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeleteSoLuong", ReplyAction="http://tempuri.org/IAdminWinform/DeleteSoLuongResponse")]
        System.Threading.Tasks.Task<bool> DeleteSoLuongAsync(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertSanPham", ReplyAction="http://tempuri.org/IAdminWinform/InsertSanPhamResponse")]
        bool InsertSanPham(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertSanPham", ReplyAction="http://tempuri.org/IAdminWinform/InsertSanPhamResponse")]
        System.Threading.Tasks.Task<bool> InsertSanPhamAsync(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeleteSanPham", ReplyAction="http://tempuri.org/IAdminWinform/DeleteSanPhamResponse")]
        bool DeleteSanPham(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeleteSanPham", ReplyAction="http://tempuri.org/IAdminWinform/DeleteSanPhamResponse")]
        System.Threading.Tasks.Task<bool> DeleteSanPhamAsync(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateSanPham", ReplyAction="http://tempuri.org/IAdminWinform/UpdateSanPhamResponse")]
        bool UpdateSanPham(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateSanPham", ReplyAction="http://tempuri.org/IAdminWinform/UpdateSanPhamResponse")]
        System.Threading.Tasks.Task<bool> UpdateSanPhamAsync(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllPhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/FindAllPhanLoaiResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[] FindAllPhanLoai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllPhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/FindAllPhanLoaiResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[]> FindAllPhanLoaiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindPhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/FindPhanLoaiResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[] FindPhanLoai(string mapl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindPhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/FindPhanLoaiResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[]> FindPhanLoaiAsync(string mapl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertPhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/InsertPhanLoaiResponse")]
        bool InsertPhanLoai(string mapl, string tenpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertPhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/InsertPhanLoaiResponse")]
        System.Threading.Tasks.Task<bool> InsertPhanLoaiAsync(string mapl, string tenpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeletePhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/DeletePhanLoaiResponse")]
        bool DeletePhanLoai(string mapl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/DeletePhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/DeletePhanLoaiResponse")]
        System.Threading.Tasks.Task<bool> DeletePhanLoaiAsync(string mapl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdatePhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/UpdatePhanLoaiResponse")]
        bool UpdatePhanLoai(string mapl, string tenpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdatePhanLoai", ReplyAction="http://tempuri.org/IAdminWinform/UpdatePhanLoaiResponse")]
        System.Threading.Tasks.Task<bool> UpdatePhanLoaiAsync(string mapl, string tenpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/FindAllHoaDonBanResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] FindAllHoaDonBan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/FindAllHoaDonBanResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> FindAllHoaDonBanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/FindHoaDonBanResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] FindHoaDonBan(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/FindHoaDonBanResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> FindHoaDonBanAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/InsertHoaDonBanResponse")]
        bool InsertHoaDonBan(string mahd, string tendangnhap, string tinhtrang, string hoten, string sdt, string diachi, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/InsertHoaDonBanResponse")]
        System.Threading.Tasks.Task<bool> InsertHoaDonBanAsync(string mahd, string tendangnhap, string tinhtrang, string hoten, string sdt, string diachi, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/UpdateHoaDonBanResponse")]
        bool UpdateHoaDonBan(string mahd, string tinhtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/UpdateHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/UpdateHoaDonBanResponse")]
        System.Threading.Tasks.Task<bool> UpdateHoaDonBanAsync(string mahd, string tinhtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindChiTietHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/FindChiTietHoaDonBanResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[] FindChiTietHoaDonBan(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindChiTietHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/FindChiTietHoaDonBanResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[]> FindChiTietHoaDonBanAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonBanResponse")]
        bool InsertChiTietHoaDonBan(string mahd, string masp, int soluong, int gia, int giagiam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonBan", ReplyAction="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonBanResponse")]
        System.Threading.Tasks.Task<bool> InsertChiTietHoaDonBanAsync(string mahd, string masp, int soluong, int gia, int giagiam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/FindAllHoaDonNhapResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[] FindAllHoaDonNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindAllHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/FindAllHoaDonNhapResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[]> FindAllHoaDonNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/FindHoaDonNhapResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[] FindHoaDonNhap(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/FindHoaDonNhapResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[]> FindHoaDonNhapAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/InsertHoaDonNhapResponse")]
        bool InsertHoaDonNhap(string mahd, string tendangnhap, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/InsertHoaDonNhapResponse")]
        System.Threading.Tasks.Task<bool> InsertHoaDonNhapAsync(string mahd, string tendangnhap, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindChiTietHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/FindChiTietHoaDonNhapResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[] FindChiTietHoaDonNhap(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/FindChiTietHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/FindChiTietHoaDonNhapResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[]> FindChiTietHoaDonNhapAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonNhapResponse")]
        bool InsertChiTietHoaDonNhap(string mahd, string masp, int soluong, int gia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonNhap", ReplyAction="http://tempuri.org/IAdminWinform/InsertChiTietHoaDonNhapResponse")]
        System.Threading.Tasks.Task<bool> InsertChiTietHoaDonNhapAsync(string mahd, string masp, int soluong, int gia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/ThongKeTheoNgay", ReplyAction="http://tempuri.org/IAdminWinform/ThongKeTheoNgayResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] ThongKeTheoNgay(string ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/ThongKeTheoNgay", ReplyAction="http://tempuri.org/IAdminWinform/ThongKeTheoNgayResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> ThongKeTheoNgayAsync(string ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/ThongKeTheoThang", ReplyAction="http://tempuri.org/IAdminWinform/ThongKeTheoThangResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] ThongKeTheoThang(string thang, string nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/ThongKeTheoThang", ReplyAction="http://tempuri.org/IAdminWinform/ThongKeTheoThangResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> ThongKeTheoThangAsync(string thang, string nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/ThongKeTheoNam", ReplyAction="http://tempuri.org/IAdminWinform/ThongKeTheoNamResponse")]
        WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] ThongKeTheoNam(string nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminWinform/ThongKeTheoNam", ReplyAction="http://tempuri.org/IAdminWinform/ThongKeTheoNamResponse")]
        System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> ThongKeTheoNamAsync(string nam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminWinformChannel : WindowsFormGiayPatin.ServiceReferenceAdmin.IAdminWinform, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminWinformClient : System.ServiceModel.ClientBase<WindowsFormGiayPatin.ServiceReferenceAdmin.IAdminWinform>, WindowsFormGiayPatin.ServiceReferenceAdmin.IAdminWinform {
        
        public AdminWinformClient() {
        }
        
        public AdminWinformClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminWinformClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminWinformClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminWinformClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[] FindAllNguoiDung() {
            return base.Channel.FindAllNguoiDung();
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[]> FindAllNguoiDungAsync() {
            return base.Channel.FindAllNguoiDungAsync();
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[] FindNguoiDung(string tendangnhap) {
            return base.Channel.FindNguoiDung(tendangnhap);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.NguoiDung[]> FindNguoiDungAsync(string tendangnhap) {
            return base.Channel.FindNguoiDungAsync(tendangnhap);
        }
        
        public bool DangNhapNguoiDung(string tendangnhap, string matkhau) {
            return base.Channel.DangNhapNguoiDung(tendangnhap, matkhau);
        }
        
        public System.Threading.Tasks.Task<bool> DangNhapNguoiDungAsync(string tendangnhap, string matkhau) {
            return base.Channel.DangNhapNguoiDungAsync(tendangnhap, matkhau);
        }
        
        public bool InsertNguoiDung(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.InsertNguoiDung(tendangnhap, matkhau, hoten, quyen, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNguoiDungAsync(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.InsertNguoiDungAsync(tendangnhap, matkhau, hoten, quyen, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public bool DeleteNguoiDung(string tendangnhap) {
            return base.Channel.DeleteNguoiDung(tendangnhap);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteNguoiDungAsync(string tendangnhap) {
            return base.Channel.DeleteNguoiDungAsync(tendangnhap);
        }
        
        public bool UpdateNguoiDung(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.UpdateNguoiDung(tendangnhap, matkhau, hoten, quyen, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateNguoiDungAsync(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.UpdateNguoiDungAsync(tendangnhap, matkhau, hoten, quyen, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[] FindAllSanPham() {
            return base.Channel.FindAllSanPham();
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[]> FindAllSanPhamAsync() {
            return base.Channel.FindAllSanPhamAsync();
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[] FindSanPham(string tensp) {
            return base.Channel.FindSanPham(tensp);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham[]> FindSanPhamAsync(string tensp) {
            return base.Channel.FindSanPhamAsync(tensp);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham FindMaSanPham(string masp) {
            return base.Channel.FindMaSanPham(masp);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.SanPham> FindMaSanPhamAsync(string masp) {
            return base.Channel.FindMaSanPhamAsync(masp);
        }
        
        public bool UpdateSoLuong(string masp, int soluong) {
            return base.Channel.UpdateSoLuong(masp, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSoLuongAsync(string masp, int soluong) {
            return base.Channel.UpdateSoLuongAsync(masp, soluong);
        }
        
        public bool DeleteSoLuong(string masp, int soluong) {
            return base.Channel.DeleteSoLuong(masp, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSoLuongAsync(string masp, int soluong) {
            return base.Channel.DeleteSoLuongAsync(masp, soluong);
        }
        
        public bool InsertSanPham(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh) {
            return base.Channel.InsertSanPham(masp, tensp, maloai, baohanh, trangthai, loaimau, kichco, soluong, gia, giagiam, hinhanh);
        }
        
        public System.Threading.Tasks.Task<bool> InsertSanPhamAsync(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh) {
            return base.Channel.InsertSanPhamAsync(masp, tensp, maloai, baohanh, trangthai, loaimau, kichco, soluong, gia, giagiam, hinhanh);
        }
        
        public bool DeleteSanPham(string masp) {
            return base.Channel.DeleteSanPham(masp);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSanPhamAsync(string masp) {
            return base.Channel.DeleteSanPhamAsync(masp);
        }
        
        public bool UpdateSanPham(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh) {
            return base.Channel.UpdateSanPham(masp, tensp, maloai, baohanh, trangthai, loaimau, kichco, soluong, gia, giagiam, hinhanh);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSanPhamAsync(string masp, string tensp, string maloai, int baohanh, string trangthai, string loaimau, string kichco, int soluong, int gia, int giagiam, string hinhanh) {
            return base.Channel.UpdateSanPhamAsync(masp, tensp, maloai, baohanh, trangthai, loaimau, kichco, soluong, gia, giagiam, hinhanh);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[] FindAllPhanLoai() {
            return base.Channel.FindAllPhanLoai();
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[]> FindAllPhanLoaiAsync() {
            return base.Channel.FindAllPhanLoaiAsync();
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[] FindPhanLoai(string mapl) {
            return base.Channel.FindPhanLoai(mapl);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.PhanLoai[]> FindPhanLoaiAsync(string mapl) {
            return base.Channel.FindPhanLoaiAsync(mapl);
        }
        
        public bool InsertPhanLoai(string mapl, string tenpl) {
            return base.Channel.InsertPhanLoai(mapl, tenpl);
        }
        
        public System.Threading.Tasks.Task<bool> InsertPhanLoaiAsync(string mapl, string tenpl) {
            return base.Channel.InsertPhanLoaiAsync(mapl, tenpl);
        }
        
        public bool DeletePhanLoai(string mapl) {
            return base.Channel.DeletePhanLoai(mapl);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePhanLoaiAsync(string mapl) {
            return base.Channel.DeletePhanLoaiAsync(mapl);
        }
        
        public bool UpdatePhanLoai(string mapl, string tenpl) {
            return base.Channel.UpdatePhanLoai(mapl, tenpl);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePhanLoaiAsync(string mapl, string tenpl) {
            return base.Channel.UpdatePhanLoaiAsync(mapl, tenpl);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] FindAllHoaDonBan() {
            return base.Channel.FindAllHoaDonBan();
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> FindAllHoaDonBanAsync() {
            return base.Channel.FindAllHoaDonBanAsync();
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] FindHoaDonBan(string mahd) {
            return base.Channel.FindHoaDonBan(mahd);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> FindHoaDonBanAsync(string mahd) {
            return base.Channel.FindHoaDonBanAsync(mahd);
        }
        
        public bool InsertHoaDonBan(string mahd, string tendangnhap, string tinhtrang, string hoten, string sdt, string diachi, float tongtien) {
            return base.Channel.InsertHoaDonBan(mahd, tendangnhap, tinhtrang, hoten, sdt, diachi, tongtien);
        }
        
        public System.Threading.Tasks.Task<bool> InsertHoaDonBanAsync(string mahd, string tendangnhap, string tinhtrang, string hoten, string sdt, string diachi, float tongtien) {
            return base.Channel.InsertHoaDonBanAsync(mahd, tendangnhap, tinhtrang, hoten, sdt, diachi, tongtien);
        }
        
        public bool UpdateHoaDonBan(string mahd, string tinhtrang) {
            return base.Channel.UpdateHoaDonBan(mahd, tinhtrang);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateHoaDonBanAsync(string mahd, string tinhtrang) {
            return base.Channel.UpdateHoaDonBanAsync(mahd, tinhtrang);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[] FindChiTietHoaDonBan(string mahd) {
            return base.Channel.FindChiTietHoaDonBan(mahd);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonBan[]> FindChiTietHoaDonBanAsync(string mahd) {
            return base.Channel.FindChiTietHoaDonBanAsync(mahd);
        }
        
        public bool InsertChiTietHoaDonBan(string mahd, string masp, int soluong, int gia, int giagiam) {
            return base.Channel.InsertChiTietHoaDonBan(mahd, masp, soluong, gia, giagiam);
        }
        
        public System.Threading.Tasks.Task<bool> InsertChiTietHoaDonBanAsync(string mahd, string masp, int soluong, int gia, int giagiam) {
            return base.Channel.InsertChiTietHoaDonBanAsync(mahd, masp, soluong, gia, giagiam);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[] FindAllHoaDonNhap() {
            return base.Channel.FindAllHoaDonNhap();
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[]> FindAllHoaDonNhapAsync() {
            return base.Channel.FindAllHoaDonNhapAsync();
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[] FindHoaDonNhap(string mahd) {
            return base.Channel.FindHoaDonNhap(mahd);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonNhap[]> FindHoaDonNhapAsync(string mahd) {
            return base.Channel.FindHoaDonNhapAsync(mahd);
        }
        
        public bool InsertHoaDonNhap(string mahd, string tendangnhap, float tongtien) {
            return base.Channel.InsertHoaDonNhap(mahd, tendangnhap, tongtien);
        }
        
        public System.Threading.Tasks.Task<bool> InsertHoaDonNhapAsync(string mahd, string tendangnhap, float tongtien) {
            return base.Channel.InsertHoaDonNhapAsync(mahd, tendangnhap, tongtien);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[] FindChiTietHoaDonNhap(string mahd) {
            return base.Channel.FindChiTietHoaDonNhap(mahd);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.CTHoaDonNhap[]> FindChiTietHoaDonNhapAsync(string mahd) {
            return base.Channel.FindChiTietHoaDonNhapAsync(mahd);
        }
        
        public bool InsertChiTietHoaDonNhap(string mahd, string masp, int soluong, int gia) {
            return base.Channel.InsertChiTietHoaDonNhap(mahd, masp, soluong, gia);
        }
        
        public System.Threading.Tasks.Task<bool> InsertChiTietHoaDonNhapAsync(string mahd, string masp, int soluong, int gia) {
            return base.Channel.InsertChiTietHoaDonNhapAsync(mahd, masp, soluong, gia);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] ThongKeTheoNgay(string ngay) {
            return base.Channel.ThongKeTheoNgay(ngay);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> ThongKeTheoNgayAsync(string ngay) {
            return base.Channel.ThongKeTheoNgayAsync(ngay);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] ThongKeTheoThang(string thang, string nam) {
            return base.Channel.ThongKeTheoThang(thang, nam);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> ThongKeTheoThangAsync(string thang, string nam) {
            return base.Channel.ThongKeTheoThangAsync(thang, nam);
        }
        
        public WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[] ThongKeTheoNam(string nam) {
            return base.Channel.ThongKeTheoNam(nam);
        }
        
        public System.Threading.Tasks.Task<WindowsFormGiayPatin.ServiceReferenceAdmin.HoaDonBan[]> ThongKeTheoNamAsync(string nam) {
            return base.Channel.ThongKeTheoNamAsync(nam);
        }
    }
}
