//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGiayPatin.ServiceReferenceUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NguoiDung", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class NguoiDung : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.HoaDonBan[] HoaDonBansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.HoaDonNhap[] HoaDonNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.HoaDonBan[] HoaDonBans {
            get {
                return this.HoaDonBansField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonBansField, value) != true)) {
                    this.HoaDonBansField = value;
                    this.RaisePropertyChanged("HoaDonBans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.HoaDonNhap[] HoaDonNhaps {
            get {
                return this.HoaDonNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonNhapsField, value) != true)) {
                    this.HoaDonNhapsField = value;
                    this.RaisePropertyChanged("HoaDonNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quyen {
            get {
                return this.QuyenField;
            }
            set {
                if ((this.QuyenField.Equals(value) != true)) {
                    this.QuyenField = value;
                    this.RaisePropertyChanged("Quyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoaDonBan", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class HoaDonBan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[] CTHoaDonBansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayDatHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayGiaoHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.NguoiDung NguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[] CTHoaDonBans {
            get {
                return this.CTHoaDonBansField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonBansField, value) != true)) {
                    this.CTHoaDonBansField = value;
                    this.RaisePropertyChanged("CTHoaDonBans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaHoaDon {
            get {
                return this.MaHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHoaDonField, value) != true)) {
                    this.MaHoaDonField = value;
                    this.RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayDatHang {
            get {
                return this.NgayDatHangField;
            }
            set {
                if ((this.NgayDatHangField.Equals(value) != true)) {
                    this.NgayDatHangField = value;
                    this.RaisePropertyChanged("NgayDatHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayGiaoHang {
            get {
                return this.NgayGiaoHangField;
            }
            set {
                if ((this.NgayGiaoHangField.Equals(value) != true)) {
                    this.NgayGiaoHangField = value;
                    this.RaisePropertyChanged("NgayGiaoHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.NguoiDung NguoiDung {
            get {
                return this.NguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiDungField, value) != true)) {
                    this.NguoiDungField = value;
                    this.RaisePropertyChanged("NguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhTrangField, value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoaDonNhap", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class HoaDonNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.CTHoaDonNhap[] CTHoaDonNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.NguoiDung NguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.CTHoaDonNhap[] CTHoaDonNhaps {
            get {
                return this.CTHoaDonNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonNhapsField, value) != true)) {
                    this.CTHoaDonNhapsField = value;
                    this.RaisePropertyChanged("CTHoaDonNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaHoaDon {
            get {
                return this.MaHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHoaDonField, value) != true)) {
                    this.MaHoaDonField = value;
                    this.RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.NguoiDung NguoiDung {
            get {
                return this.NguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiDungField, value) != true)) {
                    this.NguoiDungField = value;
                    this.RaisePropertyChanged("NguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTHoaDonBan", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class CTHoaDonBan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaGiamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.HoaDonBan HoaDonBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaCTHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GiaGiam {
            get {
                return this.GiaGiamField;
            }
            set {
                if ((this.GiaGiamField.Equals(value) != true)) {
                    this.GiaGiamField = value;
                    this.RaisePropertyChanged("GiaGiam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.HoaDonBan HoaDonBan {
            get {
                return this.HoaDonBanField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonBanField, value) != true)) {
                    this.HoaDonBanField = value;
                    this.RaisePropertyChanged("HoaDonBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaCTHoaDon {
            get {
                return this.MaCTHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaCTHoaDonField, value) != true)) {
                    this.MaCTHoaDonField = value;
                    this.RaisePropertyChanged("MaCTHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSPField, value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BaoHanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[] CTHoaDonBansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.CTHoaDonNhap[] CTHoaDonNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaGiamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KichCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.PhanLoai PhanLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhTrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaoHanh {
            get {
                return this.BaoHanhField;
            }
            set {
                if ((this.BaoHanhField.Equals(value) != true)) {
                    this.BaoHanhField = value;
                    this.RaisePropertyChanged("BaoHanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[] CTHoaDonBans {
            get {
                return this.CTHoaDonBansField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonBansField, value) != true)) {
                    this.CTHoaDonBansField = value;
                    this.RaisePropertyChanged("CTHoaDonBans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.CTHoaDonNhap[] CTHoaDonNhaps {
            get {
                return this.CTHoaDonNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHoaDonNhapsField, value) != true)) {
                    this.CTHoaDonNhapsField = value;
                    this.RaisePropertyChanged("CTHoaDonNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GiaGiam {
            get {
                return this.GiaGiamField;
            }
            set {
                if ((this.GiaGiamField.Equals(value) != true)) {
                    this.GiaGiamField = value;
                    this.RaisePropertyChanged("GiaGiam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KichCo {
            get {
                return this.KichCoField;
            }
            set {
                if ((object.ReferenceEquals(this.KichCoField, value) != true)) {
                    this.KichCoField = value;
                    this.RaisePropertyChanged("KichCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaiMau {
            get {
                return this.LoaiMauField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiMauField, value) != true)) {
                    this.LoaiMauField = value;
                    this.RaisePropertyChanged("LoaiMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiField, value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSPField, value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.PhanLoai PhanLoai {
            get {
                return this.PhanLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.PhanLoaiField, value) != true)) {
                    this.PhanLoaiField = value;
                    this.RaisePropertyChanged("PhanLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhTrangField, value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhanLoai", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class PhanLoai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.SanPham[] SanPhamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiField, value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTHoaDonNhap", Namespace="http://schemas.datacontract.org/2004/07/WedService")]
    [System.SerializableAttribute()]
    public partial class CTHoaDonNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.HoaDonNhap HoaDonNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaCTHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGiayPatin.ServiceReferenceUser.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.HoaDonNhap HoaDonNhap {
            get {
                return this.HoaDonNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.HoaDonNhapField, value) != true)) {
                    this.HoaDonNhapField = value;
                    this.RaisePropertyChanged("HoaDonNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaCTHoaDon {
            get {
                return this.MaCTHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaCTHoaDonField, value) != true)) {
                    this.MaCTHoaDonField = value;
                    this.RaisePropertyChanged("MaCTHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSPField, value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGiayPatin.ServiceReferenceUser.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUser.IUserWed")]
    public interface IUserWed {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllNguoiDung", ReplyAction="http://tempuri.org/IUserWed/FindAllNguoiDungResponse")]
        WebGiayPatin.ServiceReferenceUser.NguoiDung[] FindAllNguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllNguoiDung", ReplyAction="http://tempuri.org/IUserWed/FindAllNguoiDungResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.NguoiDung[]> FindAllNguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindNguoiDung", ReplyAction="http://tempuri.org/IUserWed/FindNguoiDungResponse")]
        WebGiayPatin.ServiceReferenceUser.NguoiDung FindNguoiDung(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindNguoiDung", ReplyAction="http://tempuri.org/IUserWed/FindNguoiDungResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.NguoiDung> FindNguoiDungAsync(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/DangNhapNguoiDung", ReplyAction="http://tempuri.org/IUserWed/DangNhapNguoiDungResponse")]
        bool DangNhapNguoiDung(string tendangnhap, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/DangNhapNguoiDung", ReplyAction="http://tempuri.org/IUserWed/DangNhapNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> DangNhapNguoiDungAsync(string tendangnhap, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/InsertNguoiDung", ReplyAction="http://tempuri.org/IUserWed/InsertNguoiDungResponse")]
        bool InsertNguoiDung(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/InsertNguoiDung", ReplyAction="http://tempuri.org/IUserWed/InsertNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> InsertNguoiDungAsync(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/UpdateThongTinDangNhap", ReplyAction="http://tempuri.org/IUserWed/UpdateThongTinDangNhapResponse")]
        bool UpdateThongTinDangNhap(string tendangnhap, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/UpdateThongTinDangNhap", ReplyAction="http://tempuri.org/IUserWed/UpdateThongTinDangNhapResponse")]
        System.Threading.Tasks.Task<bool> UpdateThongTinDangNhapAsync(string tendangnhap, string matkhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/UpdateThongTinCaNhan", ReplyAction="http://tempuri.org/IUserWed/UpdateThongTinCaNhanResponse")]
        bool UpdateThongTinCaNhan(string tendangnhap, string hoten, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/UpdateThongTinCaNhan", ReplyAction="http://tempuri.org/IUserWed/UpdateThongTinCaNhanResponse")]
        System.Threading.Tasks.Task<bool> UpdateThongTinCaNhanAsync(string tendangnhap, string hoten, string ngaysinh, string gioitinh, string diachi, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSanPham", ReplyAction="http://tempuri.org/IUserWed/FindAllSanPhamResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSanPham();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSanPham", ReplyAction="http://tempuri.org/IUserWed/FindAllSanPhamResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSanPhamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPMoi", ReplyAction="http://tempuri.org/IUserWed/FindAllSPMoiResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPMoi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPMoi", ReplyAction="http://tempuri.org/IUserWed/FindAllSPMoiResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPMoiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPNoiBat", ReplyAction="http://tempuri.org/IUserWed/FindAllSPNoiBatResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPNoiBat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPNoiBat", ReplyAction="http://tempuri.org/IUserWed/FindAllSPNoiBatResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPNoiBatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPPhanLoai", ReplyAction="http://tempuri.org/IUserWed/FindAllSPPhanLoaiResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPPhanLoai(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPPhanLoai", ReplyAction="http://tempuri.org/IUserWed/FindAllSPPhanLoaiResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPPhanLoaiAsync(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPKhuyenMai", ReplyAction="http://tempuri.org/IUserWed/FindAllSPKhuyenMaiResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPKhuyenMai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllSPKhuyenMai", ReplyAction="http://tempuri.org/IUserWed/FindAllSPKhuyenMaiResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPKhuyenMaiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindSanPham", ReplyAction="http://tempuri.org/IUserWed/FindSanPhamResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham FindSanPham(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindSanPham", ReplyAction="http://tempuri.org/IUserWed/FindSanPhamResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham> FindSanPhamAsync(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/AddSoLuongSP", ReplyAction="http://tempuri.org/IUserWed/AddSoLuongSPResponse")]
        bool AddSoLuongSP(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/AddSoLuongSP", ReplyAction="http://tempuri.org/IUserWed/AddSoLuongSPResponse")]
        System.Threading.Tasks.Task<bool> AddSoLuongSPAsync(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/DeleteSoLuongSP", ReplyAction="http://tempuri.org/IUserWed/DeleteSoLuongSPResponse")]
        bool DeleteSoLuongSP(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/DeleteSoLuongSP", ReplyAction="http://tempuri.org/IUserWed/DeleteSoLuongSPResponse")]
        System.Threading.Tasks.Task<bool> DeleteSoLuongSPAsync(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllPhanLoai", ReplyAction="http://tempuri.org/IUserWed/FindAllPhanLoaiResponse")]
        WebGiayPatin.ServiceReferenceUser.PhanLoai[] FindAllPhanLoai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllPhanLoai", ReplyAction="http://tempuri.org/IUserWed/FindAllPhanLoaiResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.PhanLoai[]> FindAllPhanLoaiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindPhanLoai", ReplyAction="http://tempuri.org/IUserWed/FindPhanLoaiResponse")]
        string FindPhanLoai(string mapl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindPhanLoai", ReplyAction="http://tempuri.org/IUserWed/FindPhanLoaiResponse")]
        System.Threading.Tasks.Task<string> FindPhanLoaiAsync(string mapl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/FindAllHoaDonBanResponse")]
        WebGiayPatin.ServiceReferenceUser.HoaDonBan[] FindAllHoaDonBan(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindAllHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/FindAllHoaDonBanResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.HoaDonBan[]> FindAllHoaDonBanAsync(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/FindHoaDonBanResponse")]
        WebGiayPatin.ServiceReferenceUser.HoaDonBan FindHoaDonBan(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/FindHoaDonBanResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.HoaDonBan> FindHoaDonBanAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindHoaDonBanTheoNgay", ReplyAction="http://tempuri.org/IUserWed/FindHoaDonBanTheoNgayResponse")]
        WebGiayPatin.ServiceReferenceUser.HoaDonBan[] FindHoaDonBanTheoNgay(string tendangnhap, System.Nullable<System.DateTime> ngaytu, System.Nullable<System.DateTime> ngayden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindHoaDonBanTheoNgay", ReplyAction="http://tempuri.org/IUserWed/FindHoaDonBanTheoNgayResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.HoaDonBan[]> FindHoaDonBanTheoNgayAsync(string tendangnhap, System.Nullable<System.DateTime> ngaytu, System.Nullable<System.DateTime> ngayden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/InsertHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/InsertHoaDonBanResponse")]
        bool InsertHoaDonBan(string mahd, string tendangnhap, string hoten, string sdt, string diachi, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/InsertHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/InsertHoaDonBanResponse")]
        System.Threading.Tasks.Task<bool> InsertHoaDonBanAsync(string mahd, string tendangnhap, string hoten, string sdt, string diachi, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/HuyHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/HuyHoaDonBanResponse")]
        bool HuyHoaDonBan(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/HuyHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/HuyHoaDonBanResponse")]
        System.Threading.Tasks.Task<bool> HuyHoaDonBanAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindChiTietHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/FindChiTietHoaDonBanResponse")]
        WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[] FindChiTietHoaDonBan(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindChiTietHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/FindChiTietHoaDonBanResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[]> FindChiTietHoaDonBanAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/InsertChiTietHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/InsertChiTietHoaDonBanResponse")]
        bool InsertChiTietHoaDonBan(string mahd, string masp, int soluong, int gia, int giagiam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/InsertChiTietHoaDonBan", ReplyAction="http://tempuri.org/IUserWed/InsertChiTietHoaDonBanResponse")]
        System.Threading.Tasks.Task<bool> InsertChiTietHoaDonBanAsync(string mahd, string masp, int soluong, int gia, int giagiam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindTimKiemCB", ReplyAction="http://tempuri.org/IUserWed/FindTimKiemCBResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham[] FindTimKiemCB(string timkiem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindTimKiemCB", ReplyAction="http://tempuri.org/IUserWed/FindTimKiemCBResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindTimKiemCBAsync(string timkiem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindTimKiemNC", ReplyAction="http://tempuri.org/IUserWed/FindTimKiemNCResponse")]
        WebGiayPatin.ServiceReferenceUser.SanPham[] FindTimKiemNC(string timkiem, string phanloai, int giatu, int giaden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWed/FindTimKiemNC", ReplyAction="http://tempuri.org/IUserWed/FindTimKiemNCResponse")]
        System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindTimKiemNCAsync(string timkiem, string phanloai, int giatu, int giaden);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserWedChannel : WebGiayPatin.ServiceReferenceUser.IUserWed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWedClient : System.ServiceModel.ClientBase<WebGiayPatin.ServiceReferenceUser.IUserWed>, WebGiayPatin.ServiceReferenceUser.IUserWed {
        
        public UserWedClient() {
        }
        
        public UserWedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebGiayPatin.ServiceReferenceUser.NguoiDung[] FindAllNguoiDung() {
            return base.Channel.FindAllNguoiDung();
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.NguoiDung[]> FindAllNguoiDungAsync() {
            return base.Channel.FindAllNguoiDungAsync();
        }
        
        public WebGiayPatin.ServiceReferenceUser.NguoiDung FindNguoiDung(string tendangnhap) {
            return base.Channel.FindNguoiDung(tendangnhap);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.NguoiDung> FindNguoiDungAsync(string tendangnhap) {
            return base.Channel.FindNguoiDungAsync(tendangnhap);
        }
        
        public bool DangNhapNguoiDung(string tendangnhap, string matkhau) {
            return base.Channel.DangNhapNguoiDung(tendangnhap, matkhau);
        }
        
        public System.Threading.Tasks.Task<bool> DangNhapNguoiDungAsync(string tendangnhap, string matkhau) {
            return base.Channel.DangNhapNguoiDungAsync(tendangnhap, matkhau);
        }
        
        public bool InsertNguoiDung(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.InsertNguoiDung(tendangnhap, matkhau, hoten, quyen, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNguoiDungAsync(string tendangnhap, string matkhau, string hoten, int quyen, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.InsertNguoiDungAsync(tendangnhap, matkhau, hoten, quyen, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public bool UpdateThongTinDangNhap(string tendangnhap, string matkhau) {
            return base.Channel.UpdateThongTinDangNhap(tendangnhap, matkhau);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateThongTinDangNhapAsync(string tendangnhap, string matkhau) {
            return base.Channel.UpdateThongTinDangNhapAsync(tendangnhap, matkhau);
        }
        
        public bool UpdateThongTinCaNhan(string tendangnhap, string hoten, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.UpdateThongTinCaNhan(tendangnhap, hoten, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateThongTinCaNhanAsync(string tendangnhap, string hoten, string ngaysinh, string gioitinh, string diachi, string email, string sdt) {
            return base.Channel.UpdateThongTinCaNhanAsync(tendangnhap, hoten, ngaysinh, gioitinh, diachi, email, sdt);
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSanPham() {
            return base.Channel.FindAllSanPham();
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSanPhamAsync() {
            return base.Channel.FindAllSanPhamAsync();
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPMoi() {
            return base.Channel.FindAllSPMoi();
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPMoiAsync() {
            return base.Channel.FindAllSPMoiAsync();
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPNoiBat() {
            return base.Channel.FindAllSPNoiBat();
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPNoiBatAsync() {
            return base.Channel.FindAllSPNoiBatAsync();
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPPhanLoai(string maloai) {
            return base.Channel.FindAllSPPhanLoai(maloai);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPPhanLoaiAsync(string maloai) {
            return base.Channel.FindAllSPPhanLoaiAsync(maloai);
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham[] FindAllSPKhuyenMai() {
            return base.Channel.FindAllSPKhuyenMai();
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindAllSPKhuyenMaiAsync() {
            return base.Channel.FindAllSPKhuyenMaiAsync();
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham FindSanPham(string masp) {
            return base.Channel.FindSanPham(masp);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham> FindSanPhamAsync(string masp) {
            return base.Channel.FindSanPhamAsync(masp);
        }
        
        public bool AddSoLuongSP(string masp, int soluong) {
            return base.Channel.AddSoLuongSP(masp, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> AddSoLuongSPAsync(string masp, int soluong) {
            return base.Channel.AddSoLuongSPAsync(masp, soluong);
        }
        
        public bool DeleteSoLuongSP(string masp, int soluong) {
            return base.Channel.DeleteSoLuongSP(masp, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSoLuongSPAsync(string masp, int soluong) {
            return base.Channel.DeleteSoLuongSPAsync(masp, soluong);
        }
        
        public WebGiayPatin.ServiceReferenceUser.PhanLoai[] FindAllPhanLoai() {
            return base.Channel.FindAllPhanLoai();
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.PhanLoai[]> FindAllPhanLoaiAsync() {
            return base.Channel.FindAllPhanLoaiAsync();
        }
        
        public string FindPhanLoai(string mapl) {
            return base.Channel.FindPhanLoai(mapl);
        }
        
        public System.Threading.Tasks.Task<string> FindPhanLoaiAsync(string mapl) {
            return base.Channel.FindPhanLoaiAsync(mapl);
        }
        
        public WebGiayPatin.ServiceReferenceUser.HoaDonBan[] FindAllHoaDonBan(string tendangnhap) {
            return base.Channel.FindAllHoaDonBan(tendangnhap);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.HoaDonBan[]> FindAllHoaDonBanAsync(string tendangnhap) {
            return base.Channel.FindAllHoaDonBanAsync(tendangnhap);
        }
        
        public WebGiayPatin.ServiceReferenceUser.HoaDonBan FindHoaDonBan(string mahd) {
            return base.Channel.FindHoaDonBan(mahd);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.HoaDonBan> FindHoaDonBanAsync(string mahd) {
            return base.Channel.FindHoaDonBanAsync(mahd);
        }
        
        public WebGiayPatin.ServiceReferenceUser.HoaDonBan[] FindHoaDonBanTheoNgay(string tendangnhap, System.Nullable<System.DateTime> ngaytu, System.Nullable<System.DateTime> ngayden) {
            return base.Channel.FindHoaDonBanTheoNgay(tendangnhap, ngaytu, ngayden);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.HoaDonBan[]> FindHoaDonBanTheoNgayAsync(string tendangnhap, System.Nullable<System.DateTime> ngaytu, System.Nullable<System.DateTime> ngayden) {
            return base.Channel.FindHoaDonBanTheoNgayAsync(tendangnhap, ngaytu, ngayden);
        }
        
        public bool InsertHoaDonBan(string mahd, string tendangnhap, string hoten, string sdt, string diachi, float tongtien) {
            return base.Channel.InsertHoaDonBan(mahd, tendangnhap, hoten, sdt, diachi, tongtien);
        }
        
        public System.Threading.Tasks.Task<bool> InsertHoaDonBanAsync(string mahd, string tendangnhap, string hoten, string sdt, string diachi, float tongtien) {
            return base.Channel.InsertHoaDonBanAsync(mahd, tendangnhap, hoten, sdt, diachi, tongtien);
        }
        
        public bool HuyHoaDonBan(string mahd) {
            return base.Channel.HuyHoaDonBan(mahd);
        }
        
        public System.Threading.Tasks.Task<bool> HuyHoaDonBanAsync(string mahd) {
            return base.Channel.HuyHoaDonBanAsync(mahd);
        }
        
        public WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[] FindChiTietHoaDonBan(string mahd) {
            return base.Channel.FindChiTietHoaDonBan(mahd);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.CTHoaDonBan[]> FindChiTietHoaDonBanAsync(string mahd) {
            return base.Channel.FindChiTietHoaDonBanAsync(mahd);
        }
        
        public bool InsertChiTietHoaDonBan(string mahd, string masp, int soluong, int gia, int giagiam) {
            return base.Channel.InsertChiTietHoaDonBan(mahd, masp, soluong, gia, giagiam);
        }
        
        public System.Threading.Tasks.Task<bool> InsertChiTietHoaDonBanAsync(string mahd, string masp, int soluong, int gia, int giagiam) {
            return base.Channel.InsertChiTietHoaDonBanAsync(mahd, masp, soluong, gia, giagiam);
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham[] FindTimKiemCB(string timkiem) {
            return base.Channel.FindTimKiemCB(timkiem);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindTimKiemCBAsync(string timkiem) {
            return base.Channel.FindTimKiemCBAsync(timkiem);
        }
        
        public WebGiayPatin.ServiceReferenceUser.SanPham[] FindTimKiemNC(string timkiem, string phanloai, int giatu, int giaden) {
            return base.Channel.FindTimKiemNC(timkiem, phanloai, giatu, giaden);
        }
        
        public System.Threading.Tasks.Task<WebGiayPatin.ServiceReferenceUser.SanPham[]> FindTimKiemNCAsync(string timkiem, string phanloai, int giatu, int giaden) {
            return base.Channel.FindTimKiemNCAsync(timkiem, phanloai, giatu, giaden);
        }
    }
}
